# Generated by Django 5.2 on 2025-05-14 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_comment_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_type', models.CharField(choices=[('accurate', 'Accurate'), ('inaccurate', 'Inaccurate')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='api.priceinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_validations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('price', 'user')},
            },
        ),
    ]
