services:
  - type: web
    name: pricemap
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SETTINGS_MODULE
        value: pricemap.settings 