services:
  - type: web
    name: pricemap
    runtime: python
    buildCommand: ./build.sh
    startCommand: cd $RENDER_PROJECT_DIR && PYTHONPATH=$PYTHONPATH:$RENDER_PROJECT_DIR:$RENDER_PROJECT_DIR/PriceMapProject/backend gunicorn --chdir $RENDER_PROJECT_DIR --pythonpath $RENDER_PROJECT_DIR:$RENDER_PROJECT_DIR/PriceMapProject/backend pricemap_wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SETTINGS_MODULE
        value: pricemap.settings
      - key: PORT
        value: 8000 